name: from_zero_ui
description: Flutter UI for From Zero Orchestrator
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^3.0.1
  http: ^1.5.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  url_launcher: ^6.3.2
  go_router: ^16.2.4
  uni_links: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
